### ISSUE TITLE
Create the setting application

### ISSUE THREAD

**Issue by fernan-x** [fernan-x/mac-portfolio#32]
## 🚀 Objective

Create the setting application.

<img width="790" alt="image" src="https://user-images.githubusercontent.com/22078585/162360721-48adcff3-e989-49d7-9c78-af01aeb41ad8.png">

## 💡 Todo

* [x] Create the setting design
* [x] Configure the light / dark theme
* [x] Configure the background image
* [x] Configure language
